baseURL = "www.example.com"
languageCode = "fr-ca"
title = "Claude Dufour MMF"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.homepage]
  show_call_box = true
  hide_view_all_services = false

  [params.logo]
  mobile = "images/logo text mobile.png"
  mobile_height = "36px"
  desktop = "images/logo text 2.png"
  desktop_height = "36px"
  alt = "Claude Dufour MMF"

  [params.homepage_meta_tags]
  meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_og_title = "Claude Dufour MMF"
  meta_og_type = "website"
  meta_og_url = "https://hugo-serif.netlify.app"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"

  [params.team]
  summary_large_truncate = 120

  [params.footer]
  copyright_text = 'Thème Hugo theme par <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>, intégration par <a href="http'

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

[[menu.main]]
name = "L'équipe"
url = "/team/"
weight = 2

[[menu.main]]
name = "À propos"
url = "/about/"
weight = 3

[[menu.main]]
name = "Contactez-nous"
url = "/contact/"
weight = 4

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
